development:
  adapter: postgresql
  encoding: unicode
  database: general_courses_helper_dev
  pool: 5
  username: Yulin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: general_courses_helper_test
  pool: 5
  username: Yulin
  password:

